from pathlib import Path

SNAKE_DIR = Path(workflow.basedir)
RESULTS_DIR = SNAKE_DIR.parent / "results"
RESOURCES_DIR = SNAKE_DIR.parent / "resources"
LOG_DIR = SNAKE_DIR.parent / "logs"

DOWNSAMPLE = 5

envvars:
    "GISAIDR_USERNAME",
    "GISAIDR_PASSWORD"

include: "rules/query.smk"
include: "rules/align.smk"
include: "rules/tree.smk"

rule all:
    input:
        RESULTS_DIR / "omicron-test-aligned.fasta.treefile"
