from pathlib import Path
from hashlib import shake_256
import yaml

SNAKE_DIR = Path(workflow.basedir)
RESULTS_DIR = SNAKE_DIR.parent / "results"
RESOURCES_DIR = SNAKE_DIR.parent / "resources"
CONFIG_DIR = SNAKE_DIR.parent / "config"
LOG_DIR = SNAKE_DIR.parent / "logs"

configfile: CONFIG_DIR / "config.yml"
CONFIG_HASH = shake_256(str(config).encode()).hexdigest(6)

envvars:
    "GISAIDR_USERNAME",
    "GISAIDR_PASSWORD"

include: "rules/query.smk"
include: "rules/align.smk"
include: "rules/tree.smk"

rule all:
    input:
        RESULTS_DIR / f"config-{CONFIG_HASH}.yml",
        RESULTS_DIR / f"{config['id']}-{CONFIG_HASH}-aligned.fasta.treefile"

rule store_config:
    output:
        RESULTS_DIR / "config-{hash}.yml"
    params:
        lambda wildcards: yaml.dump(config)
    shell:
        "echo \"{params}\" > {output}"
