repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.6.1
    hooks:
      - id: snakefmt
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.0b2'
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "dev-requirements.txt"]

ci:
  skip: [poetry-export]
