name: duchene-mdap-2022
channels:
  - conda-forge
  - defaults
dependencies:
  - bioconda::snakemake==7.3.6
  - bioconda::snakefmt==0.6.0
  - just==0.10.4
  - pre-commit==2.17.0
  - black==22.3.0
  - isort==5.10.1
  - pytest==7.1.1
