id: test

query:
  gisaid:
    lineage: "BA.1"
    location: "Australia"
    collection_date_complete: true
    complete: true
    low_coverage_excl: true
    to: "2022-01-01"
    from: "2021-11-01"
  downsample: 40

align:
  mafft:
  - "--6merpair"
  - "--keeplength"
  - "--addfragments"

tree:
  iqtree2:
  - "-nt AUTO"
  - "-m HKY+G"
  - "-bb 1000"
