# Assuming that all workflow rules will require shared memory only (i.e. <= 1 node per job)
cluster: >-
  sbatch --time={resources.time}
  --mem={resources.mem}
  -c {resources.cpus}
  -o logs/{rule}-{wildcards}.out -e logs/{rule}-{wildcards}.err
  {resources.extra}
cluster-cancel: "scancel $(echo $* | grep -Eo '[0-9]+')"
jobs: 50
cores: 1
default-resources: ["time='00:15:00'", "mem='4G'", "nodes=1", "cpus=1", "extra=''"]
use-conda: true
