# Assuming that all workflow rules will require shared memory only (i.e. <= 1 node per job)
cluster: >-
  sbatch --time={resources.time}
  --mem={resources.mem}
  -c {resources.cpus}
  -o logs/{rule}_{wildcards}.out -e logs/{rule}_{wildcards}.err

jobs: 50
default-resources: [time="00:15:00", mem="4G", nodes=1, cpus=1]
use-conda: true
